### PR TITLE
Eclipse settings

### PR DESCRIPTION
**Pull request by c0d3rman**
Mirroring RoboticsTeam4904/Offseason2015-A#24 changes

### CODE REVIEW

**Comment by c0d3rman** [comment]
:+1:

**Comment by nacgarg** [comment]
:+1:

**Comment by c0d3rman** [comment]
Tested - waiting on `new-motors` PR to make `master` build passing

**Comment by nacgarg** [comment]
:+1:

**Comment by nacgarg** [comment]
:+1:

**Comment by c0d3rman** [comment]
:+1:

**Pull request merged**
