### PR TITLE
Autoalign with GRIP + A Pi

### PR DESCRIPTION
**Pull request by c0d3rman**
This code autoaligns correctly during auton and teleop. It is pretty independent of the vision source as long as it can read the goal's X coordinate off of SmartDashboard.
The branch name is outdated.

### CODE REVIEW

**Comment by c0d3rman** [comment]
This PR will not be ready until RoboticsTeam4904/standard#91 is merged, as it relies on that PR. Once 91 is merged this PR should be updated with the correct version of standard.

**Comment by c0d3rman** [comment]
The merge with the new InnieControl fixes went awry, so I just copied the file from master. We need to check that it still works in this branch.

**Comment by c0d3rman** [comment]
Standard updated and issues with InnieControl fixed.

**Comment by c0d3rman** [comment]
New issue: the flashlight splits the goal in 2 on GRIP. Also, GRIP was sometimes splitting the goal by itself from some angles. Attempting to fix by adding a dilate step and making sure to back up before aligning.

**Comment by carturn** [comment]
:+1:
Not all of the autonomous routines have been tested, but enough have that the rest of them probably work.

**Pull request merged**
