### PR TITLE
switch to a mirror of apache ant

### PR DESCRIPTION
**Pull request by widdakay**

### CODE REVIEW

**Comment by c0d3rman** [comment]
Can we switch to a github-hosted repo owned by the team?
Also we need a corresponding PR on the other repos

**Comment by c0d3rman** [comment]
It seems their server is back up. @widakay do you think it's worth making the switch? (If we do, it will be to a GitHub-hosted repo)

**Comment by tylkahn** [comment]
:+1:

**Comment by c0d3rman** [comment]
Erik has confirmed that we should make the switch and that it will be GitHub-hosted.

**Comment by Sora-the-explora** [comment]
👍

**Comment by Sora-the-explora** [comment]
👍

**Pull request merged**
