### PR TITLE
Controls tim with a joystick slider

### PR DESCRIPTION
**Pull request by tylkahn**
will override the default tim command (TimSet(Tim.TimState.FULL_UP))
Controls tim with a joystick slider

### CODE REVIEW

**Comment by tylkahn** [comment]
👍

**Comment by tylkahn** [comment]
:+1:

**Comment by tylkahn** [comment]
:+1:

**Comment by tylkahn** [comment]
Makes tim controlled with a slider.

**Comment by c0d3rman** [comment]
It seems that this is no longer necessary as Tim PID is very reliable.

**Pull request closed without merging**
