### PR TITLE
RobotMap restructuring

### PR DESCRIPTION
**Pull request by c0d3rman**
Refactored RobotMap and changed ports and motors to match the robot.
Also updated to use MotorFactory.

### CODE REVIEW

**Comment by carturn** [comment]
Nathan.java is weird. You should not have to use the full paths.

**Comment by carturn** [comment]
Nathan.java is still weird.

**Comment by carturn** [comment]
Nevermind, +1

**Comment by carturn** [comment]
Nevermind, -2.

**Comment by carturn** [comment]
Nathan.java still imports from standard.humaninterface

**Comment by c0d3rman** [comment]
Tested.

**Pull request merged**
