### PR TITLE
Skynet

### PR DESCRIPTION
**Pull request by carturn**
Autonomous code.
I want to start working on this pull request. I do not think it is quite ready to merge.

### CODE REVIEW

**Comment by oldgalileo** [comment]
@carturn I am going to clean up all the print statements and whatnot, but is there anything else that is _bad_? For the most part, last night's changes weren't that drastic in the final rush, and instead it was just me tuning the values so that it actually worked.

**Comment by carturn** [comment]
Did we test the final version in teleop? If not, I think we should branch off of skynet for continued autonomous development but delay merging into master. Also, expect to wait until Sunday for further comments.

**Comment by c0d3rman** [comment]
It was not working in teleop. We will reconvene and plan at the end of
trips on Saturday.

Yoni Lerner

On Mon, Feb 22, 2016 at 10:23 AM, Carter Turnbaugh <notifications@github.com

**Comment by c0d3rman** [comment]
I have read over this code roughly; it should not affect teleop (except for the standard version, perhaps).

**Pull request merged**
